### PR TITLE
[NO-TICKET] Fix Initializing Features Values

### PR DESCRIPTION
**Pull request by eldawy-blacklane**
With the current the usage of the gem the values set the first time in
REDIS will not be loaded again unless they are removed from redis.

These values should be loaded to redis in case the file
`/config/features.yml` has been changed.

### CODE REVIEW

**Comment by RaVbaker** [comment]
I don’t agree. The file is just for seed in case no data in Redis. Redeploy of the app shouldn’t change feature flags if they’ve been changed. 

Imagine someone deployed app switched feature off and then redeploy will switch it back. It’s rather unwanted behavior.

**Comment by eldawy-blacklane** [comment]
> I don’t agree. The file is just for seed in case no data in Redis. Redeploy of the app shouldn’t change feature flags if they’ve been changed.
> 
> Imagine someone deployed app switched feature off and then redeploy will switch it back. It’s rather unwanted behavior.

But it's confusing. and the behavior is not documented anywhere. I think only having one source of truth and through it only the changes can be made is better, let's say redeploying.

**Comment by RaVbaker** [comment]
Yes, the source of truth is REDIS. :) And the file is just a fallback for defaults. But I agree that QAing this feature can be confusing. The interface to change the CanDo values in our project is in AFE - `/admin/feature_toggles`. The yaml file in project is just what should it do in case the setup wasn't specified. @eldawy-blacklane So It's all fine.

**Comment by eldawy-blacklane** [comment]
anyways it's out of this card scope. I will close the PR.

**Pull request closed without merging**
